import type {Metadata} from "next";
import {Nunito} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import Header from "@/shared/header";
import Providers from "@/components/provider";
import { Toaster } from "sonner";
import Footer from "@/shared/footer";

const nunito = Nunito({
    variable: '--font-nunito',
    subsets: ['cyrillic'],
    weight: ['400', '500', '600', '700', '800', '900']
});


export const metadata: Metadata = {
    title: "Home page | do-do-movie",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
            <body className={nunito.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Providers>
                        <Toaster position={`top-right`}/>
                        <main className={`min-h-screen px-4`}>
                            <Header/>
                            {children}
                            <Footer/>
                        </main>
                    </Providers>
                </ThemeProvider>
            </body>
            </html>
        </>
    )
}
